#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#Run the tsc command to make sure there are no TypeScript errors
#Run the eslint command to make sure there are no ESLint errors
#Format our code using prettier

yarn lint-staged